# Generated by Django 5.2.7 on 2025-10-29 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='moyenne',
            field=models.FloatField(default=0.0),
        ),
    ]
